if not exists(
select * from sys.databases
where name = 'WebDoki'
)
begin
	create database WebDoki
	CONTAINMENT = NONE
	 ON  PRIMARY 
	( NAME = N'WebDoki', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\WebDoki.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
	 LOG ON 
	( NAME = N'WebDoki_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\WebDoki_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
	 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF


	IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
	begin
	EXEC [WebDoki].[dbo].[sp_fulltext_database] @action = 'enable'
	end

	ALTER DATABASE [WebDoki] SET ANSI_NULL_DEFAULT OFF 
	ALTER DATABASE [WebDoki] SET ANSI_NULLS OFF 
	ALTER DATABASE [WebDoki] SET ANSI_PADDING OFF 
	ALTER DATABASE [WebDoki] SET ANSI_WARNINGS OFF 
	ALTER DATABASE [WebDoki] SET ARITHABORT OFF 
	ALTER DATABASE [WebDoki] SET AUTO_CLOSE OFF 
	ALTER DATABASE [WebDoki] SET AUTO_SHRINK OFF 
	ALTER DATABASE [WebDoki] SET AUTO_UPDATE_STATISTICS ON 
	ALTER DATABASE [WebDoki] SET CURSOR_CLOSE_ON_COMMIT OFF 
	ALTER DATABASE [WebDoki] SET CURSOR_DEFAULT  GLOBAL 
	ALTER DATABASE [WebDoki] SET CONCAT_NULL_YIELDS_NULL OFF 
	ALTER DATABASE [WebDoki] SET NUMERIC_ROUNDABORT OFF 
	ALTER DATABASE [WebDoki] SET QUOTED_IDENTIFIER OFF 
	ALTER DATABASE [WebDoki] SET RECURSIVE_TRIGGERS OFF 
	ALTER DATABASE [WebDoki] SET  DISABLE_BROKER 
	ALTER DATABASE [WebDoki] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
	ALTER DATABASE [WebDoki] SET DATE_CORRELATION_OPTIMIZATION OFF 
	ALTER DATABASE [WebDoki] SET TRUSTWORTHY OFF 
	ALTER DATABASE [WebDoki] SET ALLOW_SNAPSHOT_ISOLATION OFF 
	ALTER DATABASE [WebDoki] SET PARAMETERIZATION SIMPLE 
	ALTER DATABASE [WebDoki] SET READ_COMMITTED_SNAPSHOT OFF 
	ALTER DATABASE [WebDoki] SET HONOR_BROKER_PRIORITY OFF 
	ALTER DATABASE [WebDoki] SET RECOVERY FULL 
	ALTER DATABASE [WebDoki] SET  MULTI_USER 
	ALTER DATABASE [WebDoki] SET PAGE_VERIFY CHECKSUM  
	ALTER DATABASE [WebDoki] SET DB_CHAINING OFF 
	ALTER DATABASE [WebDoki] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
	ALTER DATABASE [WebDoki] SET TARGET_RECOVERY_TIME = 60 SECONDS 
	ALTER DATABASE [WebDoki] SET DELAYED_DURABILITY = DISABLED 
	ALTER DATABASE [WebDoki] SET ACCELERATED_DATABASE_RECOVERY = OFF  
	ALTER DATABASE [WebDoki] SET QUERY_STORE = ON
	ALTER DATABASE [WebDoki] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
	ALTER DATABASE [WebDoki] SET  READ_WRITE 
end